# Generated by Django 4.2.19 on 2026-04-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0016_merge_20250818_1757"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="downvotes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="rating",
            name="downvotes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="rating",
            name="title",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="userupvote",
            name="vote_type",
            field=models.CharField(
                choices=[("up", "Up"), ("down", "Down")], default="up", max_length=4
            ),
        ),
    ]
