# Generated by Django 4.2.30 on 2026-04-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0019_supplement_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_username_change",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
